arco-design-pro-vite/src/locale/index.ts

fix project start error on windows 修复了因l18n未设置allowComposition，而在win电脑下无法启动的bug

fix: fix project start error on windows

---

arco-design-pro-vite/src/api/interceptor.ts

参考了vue-element-admin的自定义请求头配置方式，在项目里新增了几乎所有项目都必须的请求头配置示例

feat: add custom headers config(JWT example)

---

arco-design-pro-vite/components.d.ts
arco-design-pro-vite/src/api/user.ts
arco-design-pro-vite/src/components/global-setting/block.vue
arco-design-pro-vite/src/components/global-setting/index.vue
arco-design-pro-vite/src/components/menu/useMenuTree.ts
arco-design-pro-vite/src/config/settings.json
arco-design-pro-vite/src/locale/en-US/settings.ts
arco-design-pro-vite/src/locale/zh-CN/settings.ts
arco-design-pro-vite/src/mock/user.ts
arco-design-pro-vite/src/router/guard/index.ts
arco-design-pro-vite/src/router/guard/serverPermission.ts
arco-design-pro-vite/src/store/modules/app/index.ts
arco-design-pro-vite/src/store/modules/app/types.ts

feat: add the configuration of the menu source server

---

arco-design-pro-vite/src/components/navbar/index.vue
arco-design-pro-vite/src/locale/en-US/settings.ts
arco-design-pro-vite/src/locale/zh-CN/settings.ts

feat: added full screen switching

---

arco-design-pro-vite/src/components/global-setting/block.vue
arco-design-pro-vite/src/components/global-setting/index.vue
arco-design-pro-vite/src/config/settings.json
arco-design-pro-vite/src/locale/en-US/settings.ts
arco-design-pro-vite/src/locale/zh-CN/settings.ts
arco-design-pro-vite/src/store/modules/app/types.ts

The color weak switch in settings will remain its default value been false, even after the user has set it to true manually.
Fixed by made the option a computed property and set its defaultValue to appStore.colorWeak.
The problem is as follows: 
After the fix:
| bugfix: 修复色弱模式选项初始值始终为 false 的问题 | bugfix: fix the problem that color weak switch's default value is always false |  |

fix: color weak switch default value not updated correctly

---

arco-design-pro-vite/src/components/menu/index.vue

feat: auto open menu

---

arco-design-pro-vite/src/views/user/setting/components/user-panel.vue

style: import spelling correction

---

arco-design-pro-vite/src/components/menu/index.vue

fix: the menu item cannot be selected after clicking the external link

---

arco-design-pro-vite/src/components/menu/index.vue

fix: expand menu logic optimization

---

arco-design-pro-vite/src/mock/user.ts

fix: 错误的注释内容

---

arco-design-pro-vite/src/hooks/visible.ts

在后台管理系统中使用visible控制各类弹出组件的场景还是挺常见的，所以希望增加一个相关的hooks
|增加useVisible|add useVisible||

feat: add useVisible

---

arco-design-pro-vite/src/views/login/components/login-form.vue

登录按钮点击后加载时可以重复点击发送请求
you can still click login button to execute login while loading
when button loading stop the login function

fix: login logic can execute while loading

---

arco-design-pro-vite/src/components/chart/index.vue

When we resize the browser window, the `chart` does not resize. 
Based on the [vue-echarts](https://github.com/ecomfe/vue-echarts#props) documentation, we should use `autoresize` instead of `auto-resize` as the props name.
| 修复图表组件缩放问题| Fix the chart component resize problem |                |

Fix vue-echarts auto resize problem

---

arco-design-pro-vite/src/views/list/search-table/index.vue
arco-design-pro-vite/src/views/list/search-table/locale/en-US.ts
arco-design-pro-vite/src/views/list/search-table/locale/zh-CN.ts
package.json

for issues https://github.com/arco-design/arco-design-pro-vue/issues/93
表格新增刷新、密度和列设置

feat(searchTable): add some setting

---

arco-design-pro-vite/src/router/routes/index.ts

Vite v3 has deprecated `import.meta.globEager`, see [migration from v2#import-meta-glob](https://vitejs.dev/guide/migration.html#import-meta-glob).
https://github.com/arco-design/arco-design-pro-vue/blob/0442d1ccda79fcc4110383c275fdce7ba9cb6294/arco-design-pro-vite/package.json#L83

refactor: use `import.meta.glob`

---

docs/changelog.md

release log 的英文文档中，第 7 行误用了中文
`问题修复`  ->  `Bugfix`

docs: update '问题修复' to 'Bugfix'

---

arco-design-pro-vite/src/views/visualization/multi-dimension-data-analysis/components/data-overview.vue

可视化显示中的数据总览组件里面echarts的series配置，描述与数据不对应，
会导致查找替换等出现意料之外的问题

fix: content does not match

---

arco-design-pro-vite/components.d.ts
arco-design-pro-vite/config/plugin/styleImport.ts
arco-design-pro-vite/package.json
arco-design-pro-vite/src/router/routes/base.ts
arco-design-pro-vite/src/views/dashboard/workplace/components/popular-content.vue
arco-design-pro-vite/yarn.lock

Feature update dependencies

---

arco-design-pro-vite/src/components/global-setting/block.vue
arco-design-pro-vite/src/components/global-setting/index.vue
arco-design-pro-vite/src/components/menu/index.vue
arco-design-pro-vite/src/components/navbar/index.vue
arco-design-pro-vite/src/config/settings.json
arco-design-pro-vite/src/layout/default-layout.vue
arco-design-pro-vite/src/locale/en-US/settings.ts
arco-design-pro-vite/src/locale/zh-CN/settings.ts
arco-design-pro-vite/src/store/modules/app/types.ts

- [✅] New feature
https://github.com/arco-design/arco-design-pro-vue/issues/182
添加顶部菜单栏开关

feat: add top menu layout config

---

arco-design-pro-vite/config/plugin/styleImport.ts

`arco-desing-vue` 中关于打包错误的 `issues`，查找错误来源为 `arco-design-pro-vue`
[#2043](https://github.com/arco-design/arco-design-vue/issues/2043)
[#2052](https://github.com/arco-design/arco-design-vue/issues/2052)
|        `vite-plugin-style-import` 插件打包错误       |       `vite-plugin-style-import` plugin build error        |     #242           |

fix: vite-plugin-style-import plugin build error

---

arco-design-pro-vite/src/components/navbar/index.vue
arco-design-pro-vite/src/hooks/locale.ts

顶部导航栏语言切换按钮 如果一直点当前设置的语言 会一直Message.success弹窗
加了个当前语言的判断 在当前语言前会显示对钩 重复设置时会在useLocale里直接return掉

feat: add check status to language button

---

arco-design-pro-vite/src/locale/index.ts

在setup中直接使用useI18n不会返回值
需要在createI18n中添加 `legacy`配置, 为`false`
https://vue-i18n.intlify.dev/guide/advanced/composition.html#basic-usage

chore: add legacy config to locale settings
